### ISSUE TITLE
Remove deprecated rubyforge_project from Gemspec.

### ISSUE THREAD

**Issue by jpickwell** [javanthropus/io-like#4]
The `rubyforge_project` Gemspec option is deprecated, and its presence produces a warning.

**Comment by javanthropus** [comment]
Thanks!  I should be able to push this out later this evening.

**Comment by javanthropus** [comment]
Unfortunately, I've allowed this project to bit rot for quite a while, so I have some work to do before I'm able to push out another release with this fix.  I appreciate the contribution.

**Comment by javanthropus** [comment]
Version 0.3.1 has been released which includes a rewritten version of your change.
